main: de.linzn.discordConnector.DiscordConnectorPlugin
name: discord-connector
version: ${project.version}
depend: [ gpt-framework ]
buildJobName: ${buildServer.jobName}
buildNumber: ${buildServer.buildNumber}